-- vim.api.nvim_create_autocmd({ "FileType" }, {
-- 	callback = function()
-- 		local filetype = vim.bo.filetype
-- 		if filetype == "alpha" then
-- 			vim.opt.laststatus = 0
-- 		else
-- 			vim.opt.laststatus = 2
-- 		end
-- 	end,
-- })
